Wovi10/AdventOfCodeCollection

2023/AdventOfCode2023/AdventOfCode2023/Day11.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day11/GalaxyPair.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day11/Universe.cs
2023/AdventOfCode2023/AdventOfCode2023/Shared/Constants.cs

MR_2023_11_02

---

2023/AdventOfCode2023/AdventOfCode2023/AdventOfCode2023.csproj
2023/AdventOfCode2023/AdventOfCode2023/Day14.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day14/Direction.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day14/Dish.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day14/DishRow.cs
2023/AdventOfCode2023/AdventOfCode2023/Shared/Constants.cs
2023/AdventOfCode2023/AdventOfCode2023/Shared/SharedMethods.cs

MR_2023_14_02

---

2023/AdventOfCode2023/AdventOfCode2023/Day16.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day16/Beam.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day16/Grid.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day16/Tile.cs
2023/AdventOfCode2023/AdventOfCode2023/Shared/Constants.cs
2023/AdventOfCode2023/AdventOfCode2023/Shared/SharedMethods.cs

MR_2023_16_02

---

2023/AdventOfCode2023/AdventOfCode2023/Day19.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day19/Aplenty.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day19/Rule.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day19/Workflow.cs
2023/AdventOfCode2023/AdventOfCode2023/Program.cs
2023/AdventOfCode2023/AdventOfCode2023/Shared/Answers.cs

MR_2023_19_02

---

2023/AdventOfCode2023/AdventOfCode2023/AdventOfCode2023.csproj
2023/AdventOfCode2023/AdventOfCode2023/Day05.cs
2023/AdventOfCode2023/AdventOfCode2023/Day20.cs
2023/AdventOfCode2023/AdventOfCode2023/Input/Day20/Day20.in
2023/AdventOfCode2023/AdventOfCode2023/Input/Day20/MockDay20Part01.in
2023/AdventOfCode2023/AdventOfCode2023/Models/Day10/Maze.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day20/DesertMachineHeadquarters.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day20/Module.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day20/Modules/BroadcastModule.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day20/Modules/ButtonModule.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day20/Modules/ConjunctionModule.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day20/Modules/FlipFlopModule.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day20/Modules/OutputModule.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day20/Modules/RxModule.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day20/Pulse.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day20/PulseModuleQueue.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day20/Utils/Constants.cs
2023/AdventOfCode2023/AdventOfCode2023/Program.cs
2023/AdventOfCode2023/AdventOfCode2023/Shared/Answers.cs
2023/AdventOfCode2023/AdventOfCode2023/Shared/SharedMethods.cs

MR_2023_20_02

---

2023/AdventOfCode2023/AdventOfCode2023/Day21.cs
2023/AdventOfCode2023/AdventOfCode2023/DayBase.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day19/Aplenty.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day19/Comparer/ComparisonStrategyFactory.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day19/Comparer/IComparisonStrategy.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day19/Comparer/Implementations/EqualsStrategy.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day19/Comparer/Implementations/GreaterThanStrategy.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day19/Comparer/Implementations/LessThanStrategy.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day21/Day21Objective
2023/AdventOfCode2023/AdventOfCode2023/Models/Day21/Garden.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day21/Tile.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day21/TileExtensions.cs
2023/AdventOfCode2023/AdventOfCode2023/Program.cs
2023/AdventOfCode2023/AdventOfCode2023/Shared/Answers.cs

MR_2023_21_02

---

2023/AdventOfCode2023/AdventOfCode2023/Day22.cs
2023/AdventOfCode2023/AdventOfCode2023/DayBase.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day22/Brick.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day22/BrickPile.cs
2023/AdventOfCode2023/AdventOfCode2023/Program.cs

MR_2023_22_02

---

2023/AdventOfCode2023/AdventOfCode2023/Day05.cs
2023/AdventOfCode2023/AdventOfCode2023/Day23.cs
2023/AdventOfCode2023/AdventOfCode2023/DayBase.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day23/Hike.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day23/HikeSegment.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day23/SnowIsland.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day23/SnowIslandExtensions.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day23/Tile.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day23/TileType.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day23/TileTypes/DefaultPath.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day23/TileTypes/DownWardsSlope.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day23/TileTypes/Forest.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day23/TileTypes/RightWardsSlope.cs
2023/AdventOfCode2023/AdventOfCode2023/Program.cs
2023/AdventOfCode2023/AdventOfCode2023/Shared/Answers.cs

MR_2023_23_02

---

2023/AdventOfCode2023/AdventOfCode2023/Day24.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day24/Hail.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day24/HailStorm.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day24/Vector3.cs
2023/AdventOfCode2023/AdventOfCode2023/Program.cs
2023/AdventOfCode2023/AdventOfCode2023/Shared/Answers.cs

MR_2023_24_02

---

2023/AdventOfCode2023/AdventOfCode2023/AdventOfCode2023.csproj
2023/AdventOfCode2023/AdventOfCode2023/Day25.cs
2023/AdventOfCode2023/AdventOfCode2023/Input/Day25/Day25.in
2023/AdventOfCode2023/AdventOfCode2023/Input/Day25/Exercise.txt
2023/AdventOfCode2023/AdventOfCode2023/Input/Day25/MockDay25.in
2023/AdventOfCode2023/AdventOfCode2023/Models/Day25/Edge.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day25/Node.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day25/Walker.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day25/WeatherMachine.cs
2023/AdventOfCode2023/AdventOfCode2023/Models/Day25/WeatherMachineExtensions.cs
2023/AdventOfCode2023/AdventOfCode2023/Program.cs

MR_2023_25_01

---

AdventOfCode/2024/Day01.cs
AdventOfCode/2024/Models/Day01Extensions.cs
AdventOfCode/2024/Program.cs
AdventOfCode/AOC.Utils/Answers.cs

MR_2024_01_02

---

AdventOfCode/2024/Day02.cs
AdventOfCode/2024/Models/Day02/Report.cs
AdventOfCode/2024/Program.cs
AdventOfCode/AOC.Utils/Answers.cs

MR_2024_02_02

---

AdventOfCode/2024/Day03.cs
AdventOfCode/2024/Input/Day03/MockDay03.in
AdventOfCode/2024/Input/Day03/MockDay03Part01.in
AdventOfCode/2024/Models/Day03/Day03Extensions.cs
AdventOfCode/2024/Program.cs
AdventOfCode/AOC.Utils/Answers.cs
AdventOfCode/AOC.Utils/SharedMethods.cs

MR_2024_03_02

---

AdventOfCode/2024/Day04.cs
AdventOfCode/2024/Models/Day04/Day04Extensions.cs
AdventOfCode/2024/Program.cs
AdventOfCode/AOC.Utils/Answers.cs

MR_2023_04_02

---

AdventOfCode/2024/Day05.cs
AdventOfCode/2024/Models/Day05/Day05Extensions.cs
AdventOfCode/2024/Models/Day05/SequenceRulesPair.cs
AdventOfCode/AOC.Utils/Answers.cs

MR_2024_05_02

---

AdventOfCode/2024/Day07.cs
AdventOfCode/2024/Models/Day07/Equation.cs
AdventOfCode/2024/Program.cs
AdventOfCode/AOC.Utils/Answers.cs
AdventOfCode/AOC.Utils/Constants.cs

MR_2024_07_02

---

AdventOfCode/2024/Day08.cs
AdventOfCode/2024/Models/Day08/Coordinate.cs
AdventOfCode/2024/Models/Day08/Location.cs
AdventOfCode/2024/Models/Day08/Map.cs
AdventOfCode/2024/Program.cs
AdventOfCode/AOC.Utils/Answers.cs
AdventOfCode/AOC.Utils/DayBase.cs
AdventOfCode/AdventOfCode.sln.DotSettings

MR_2024_08_02

---

AdventOfCode/2024/Day09.cs
AdventOfCode/2024/Models/Day09/Day09Extensions.cs
AdventOfCode/2024/Models/Day09/Disk.cs
AdventOfCode/2024/Models/Day09/File.cs
AdventOfCode/2024/Program.cs
AdventOfCode/AOC.Utils/Answers.cs
AdventOfCode/AOC.Utils/Constants.cs

MR_2024_09_02

---

AdventOfCode/2024/Day10.cs
AdventOfCode/2024/Models/Day10/Day10Extensions.cs
AdventOfCode/2024/Models/Day10/TopoMap.cs
AdventOfCode/2024/Models/Day10/Trail.cs
AdventOfCode/2024/Models/Day10/TrailHead.cs
AdventOfCode/2024/Program.cs
AdventOfCode/AOC.Utils/Answers.cs
AdventOfCode/AOC.Utils/Constants.cs

MR_2024_10_02

---

AdventOfCode/2024/Day11.cs
AdventOfCode/2024/Models/Day11/Day11Extensions.cs
AdventOfCode/2024/Program.cs
AdventOfCode/AOC.Utils/Answers.cs
AdventOfCode/AOC.Utils/DayBase.cs

MR_2024_11_02

---

AdventOfCode/2024/Day14.cs
AdventOfCode/2024/Models/Day14/Day14Extensions.cs
AdventOfCode/2024/Program.cs
AdventOfCode/AOC.Utils/Answers.cs

MR_2024_14_02

---

AdventOfCode/2024/Day15.cs
AdventOfCode/2024/Models/Day15/Day15Extensions.cs
AdventOfCode/2024/Models/Day15/ObjectType.cs
AdventOfCode/2024/Models/Day15/WarehousePart2.cs
AdventOfCode/2024/Models/Day15/WarehouseWithInstructionsPart2.cs
AdventOfCode/2024/Program.cs
AdventOfCode/AOC.Utils/Answers.cs

MR_2024_15_02

---

AdventOfCode/2024/Day17.cs
AdventOfCode/2024/Input/Day17/Day17.in
AdventOfCode/2024/Input/Day17/MockDay17.in
AdventOfCode/2024/Models/Day16/Maze.cs
AdventOfCode/2024/Models/Day17/Computer.cs
AdventOfCode/2024/Models/Day17/Day17Extensions.cs
AdventOfCode/2024/Program.cs
AdventOfCode/AOC.Utils/Answers.cs
AdventOfCode/AOC.Utils/Constants.cs
AdventOfCode/AOC.Utils/DayBase.cs
AdventOfCode/AdventOfCode.sln.DotSettings

MR_2024_17_01
